import { PortalItem } from './portal.models';

export const PORTAL_ITEMS: PortalItem[] = [
  {
    id: 'email',
    labelKey: 'items.email',
    url: 'https://mail.google.com/mail/',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'email',
  },
  {
    id: 'hr-self-service',
    labelKey: 'items.hrSelfService',
    url: 'https://hr.tanmeyah.lan/my',
    color: 'blue',
    external: true,
    iconType: 'img',
    iconSrc: 'assets/images/PortalAssets/SVG/vuesax-bold-personalcard.svg',
  },
  {
    id: 'intranet',
    labelKey: 'items.intranet',
    url: 'https://intranet.tanmeyah.lan/',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'document',
  },
  {
    id: 'help-desk',
    labelKey: 'items.helpDesk',
    url: 'https://helpdesk.tanmeyah.lan:8181/',
    color: 'blue',
    external: true,
    iconType: 'inline',
    iconName: 'ticket',
  },
  {
    id: 'crm',
    labelKey: 'items.crm',
    url: 'https://crm.tanmeyah.lan/',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'headphone',
  },
  {
    id: 'digital-payment',
    labelKey: 'items.digitalPayment',
    url: 'https://dpdb.tanmeyah.lan:4000',
    color: 'blue',
    external: true,
    iconType: 'inline',
    iconName: 'payment',
  },
  {
    id: 'attendance',
    labelKey: 'items.attendance',
    url: 'https://172.31.0.66/',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'calendar',
  },
  {
    id: 'score-card',
    labelKey: 'items.scoreCard',
    url: 'https://scorecard.tanmeyah.lan/login',
    color: 'blue',
    external: true,
    iconType: 'inline',
    iconName: 'checklist',
  },
  {
    id: 'process',
    labelKey: 'items.process',
    url: 'https://process.tanmeyah.lan/web/login',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'briefcase',
  },
  {
    id: 'erp',
    labelKey: 'items.erp',
    url: 'https://erpt.tanmeyah.lan:4445/',
    color: 'blue',
    external: true,
    iconType: 'img',
    iconSrc: 'assets/images/PortalAssets/SVG/vuesax-bold-barcode.svg',
  },

  {
    id: 'password',
    labelKey: 'items.password',
    url: 'https://ssp.tanmeyah.lan/',
    color: 'blue',
    external: true,
    iconType: 'inline',
    iconName: 'key',
  },
  {
    id: 'fmc',
    labelKey: 'items.fmc',
    url: 'https://fmc-uat.tanmeyah.lan/#/auth/login',
    color: 'red',
    external: true,
    iconType: 'inline',
    iconName: 'fmc',
  },
];
